from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional

from playwright.sync_api import sync_playwright


def _dump_python_module(payload: Dict[str, Any], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    module = (
        "# Auto-generated by worker/record_stayspdp_template.py\n"
        "# Do not edit manually.\n\n"
        "HARDCODED_STAYS_PDP_TEMPLATE = "
        f"{body}\n"
    )
    out_path.write_text(module, encoding="utf-8")


def capture_stays_pdp_template(
    listing_url: str,
    timeout_ms: int = 30000,
) -> Dict[str, Any]:
    captured: Optional[Dict[str, Any]] = None

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/121.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 800},
        )
        page = context.new_page()

        def on_request(request) -> None:
            nonlocal captured
            if captured is not None:
                return
            if request.method != "POST":
                return
            if "/api/v3/StaysPdpSections/" not in request.url:
                return
            try:
                captured = {
                    "url": request.url,
                    "headers": request.headers,
                    "post_data": request.post_data_json,
                }
            except Exception:
                captured = None

        page.on("request", on_request)
        try:
            page.goto(listing_url, wait_until="domcontentloaded", timeout=timeout_ms)
            page.wait_for_timeout(1500)
            page.mouse.wheel(0, 1800)
            for _ in range(30):
                if captured is not None:
                    break
                page.wait_for_timeout(500)
        finally:
            browser.close()

    if captured is None:
        raise RuntimeError("Timed out waiting for StaysPdpSections request capture.")
    return captured


def main() -> None:
    parser = argparse.ArgumentParser(description="Capture and hardcode StaysPdpSections template.")
    parser.add_argument(
        "--listing-url",
        required=True,
        help="Airbnb listing URL including check_in/check_out query params.",
    )
    parser.add_argument(
        "--out",
        default="worker/scraper/stayspdp_template.py",
        help="Output Python module path.",
    )
    parser.add_argument(
        "--timeout-ms",
        type=int,
        default=30000,
        help="Navigation timeout in milliseconds.",
    )
    args = parser.parse_args()

    payload = capture_stays_pdp_template(args.listing_url, timeout_ms=args.timeout_ms)
    out_path = Path(args.out)
    _dump_python_module(payload, out_path)
    print(f"Wrote hardcoded StaysPdpSections template to: {out_path}")


if __name__ == "__main__":
    main()

